# Forest Fires

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('forestfires.csv')

In [3]:
df.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0  ...         0   
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0  ...         0   
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0  ...         0   
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2  ...         0   
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0          small  
1         0          small  
2         0          small  
3         0          small  
4         0          small  

[5 rows x 31 columns]

In [4]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   month          517 non-null    object 
 1   day            517 non-null    object 
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64  
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64  
 12  daymon         517 non-null    int64  
 13  daysat         517 non-null    int64  
 14  daysun         517 non-null    int64  
 15  daythu         517 non-null    int64  
 16  daytue         517 non-null    int64  
 17  daywed         517 non-null    int64  
 18  monthapr  

In [5]:
df.describe()

FFMC         DMC          DC         ISI        temp          RH  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean    90.644681  110.872340  547.940039    9.021663   18.889168   44.288201   
std      5.520111   64.046482  248.066192    4.559477    5.806625   16.317469   
min     18.700000    1.100000    7.900000    0.000000    2.200000   15.000000   
25%     90.200000   68.600000  437.700000    6.500000   15.500000   33.000000   
50%     91.600000  108.300000  664.200000    8.400000   19.300000   42.000000   
75%     92.900000  142.400000  713.900000   10.800000   22.800000   53.000000   
max     96.200000  291.300000  860.600000   56.100000   33.300000  100.000000   

             wind        rain         area      dayfri  ...    monthdec  \
count  517.000000  517.000000   517.000000  517.000000  ...  517.000000   
mean     4.017602    0.021663    12.847292    0.164410  ...    0.017408   
std      1.791653    0.295959    63.655818    0.371006  ...    0.130913   
min      0.400000    0.000000     0.000000    0.000000  ...    0.000000   
25%      2.700000    0.000000     0.000000    0.000000  ...    0.000000   
50%      4.000000    0.000000     0.520000    0.000000  ...    0.000000   
75%      4.900000    0.000000     6.570000    0.000000  ...    0.000000   
max      9.400000    6.400000  1090.840000    1.000000  ...    1.000000   

         monthfeb    monthjan    monthjul    monthjun    monthmar    monthmay  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     0.038685    0.003868    0.061896    0.032882    0.104449    0.003868   
std      0.193029    0.062137    0.241199    0.178500    0.306138    0.062137   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

         monthnov    monthoct    monthsep  
count  517.000000  517.000000  517.000000  
mean     0.001934    0.029014    0.332689  
std      0.043980    0.168007    0.471632  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000  
75%      0.000000    0.000000    1.000000  
max      1.000000    1.000000    1.000000  

[8 rows x 28 columns]

In [6]:
df_1= df.iloc[:,2:30]

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(df_1)
df_scaled = sc.transform(df_1)
df_scaled


array([[-8.05959472e-01, -1.32332557e+00, -1.83047676e+00, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [-8.10203395e-03, -1.17954077e+00,  4.88890915e-01, ...,
        -4.40225453e-02,  5.78503817e+00, -7.06081245e-01],
       [-8.10203395e-03, -1.04982188e+00,  5.60715454e-01, ...,
        -4.40225453e-02,  5.78503817e+00, -7.06081245e-01],
       ...,
       [-1.64008316e+00, -8.46647711e-01,  4.74768113e-01, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [ 6.80956663e-01,  5.49002541e-01,  2.69382214e-01, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [-2.02087875e+00, -1.68591332e+00, -1.78044169e+00, ...,
         2.27156334e+01, -1.72859706e-01, -7.06081245e-01]])

In [8]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 28)
pca_values = pca.fit_transform(df_scaled)
pca_values

array([[ 3.76670947e+00, -1.32025451e+00, -8.43971398e-01, ...,
        -6.53345819e-02,  4.98037274e-16, -2.73530281e-16],
       [ 3.90786263e-01,  8.31061522e-01, -1.10136513e+00, ...,
         3.42618601e-02, -9.55928328e-15,  1.15055466e-15],
       [ 6.90415596e-01,  1.17774562e+00, -1.22199841e+00, ...,
         2.63235187e-02,  2.58690766e-15, -5.66797432e-17],
       ...,
       [ 9.21634000e-01, -2.64543072e-01,  2.71921606e+00, ...,
        -2.97865814e-01, -1.84247930e-16,  2.36645381e-16],
       [-1.62054896e+00, -9.78838231e-01,  3.31987355e-01, ...,
         3.91949863e-02, -2.30354869e-16,  2.72058887e-16],
       [ 4.07590654e+00, -3.67440726e-01, -2.47151775e-01, ...,
        -2.50420726e-02,  5.70142521e-17,  8.50237385e-17]])

In [9]:
import numpy as np
var = pca.explained_variance_ratio_
var1 = np.cumsum(np.round(var,decimals = 4)*100)
var1

array([13.55, 20.41, 26.65, 31.98, 36.74, 41.42, 45.79, 50.07, 54.16,
       58.18, 62.11, 65.94, 69.58, 73.21, 76.79, 80.29, 83.64, 86.89,
       89.93, 92.93, 95.3 , 97.38, 98.56, 99.45, 99.91, 99.99, 99.99,
       99.99])

In [10]:
finaldf = pd.concat([pd.DataFrame(pca_values[:,0:24],columns=['pc1','pc2','pc3','pc4','pc5','pc6','pc7',
 'pc8','pc9','pc10','pc11','pc12','pc13','pc14',
 'pc15','pc16','pc17','pc18','pc19','pc20','pc21',
 'pc22','pc23','pc24']),
 df[['size_category']]], axis = 1)
finaldf.size_category.replace(('large','small'),(1,0),inplace=True)
finaldf

pc1       pc2       pc3       pc4       pc5       pc6       pc7  \
0    3.766709 -1.320255 -0.843971 -1.994738 -1.453359  0.693985  0.308104   
1    0.390786  0.831062 -1.101365  1.400671  2.869388  0.965898 -2.795574   
2    0.690416  1.177746 -1.221998  2.442038  1.090630  0.390801 -1.586675   
3    3.359951 -1.161443  0.385728 -2.118328 -1.949601  1.027664 -0.179422   
4    2.974329 -0.842626  1.327788  0.038086 -1.124763 -0.574676 -0.777155   
..        ...       ...       ...       ...       ...       ...       ...   
512 -0.087560  0.153964  1.241810  1.536581  0.372425 -1.133422 -0.362287   
513  0.794366 -0.083966  2.670485  0.284995  0.223323 -0.904232 -0.014849   
514  0.921634 -0.264543  2.719216 -0.019643  0.242195 -0.966939 -0.118080   
515 -1.620549 -0.978838  0.331987  1.256638 -0.408164  0.735698  0.815510   
516  4.075907 -0.367441 -0.247152  0.979966  6.792273  5.943666 -1.639583   

          pc8       pc9      pc10  ...       pc16      pc17      pc18  \
0   -0.019764  0.010161 -0.437314  ...  -0.197543 -0.021839  0.688958   
1    0.041095 -0.548879  0.104500  ...  -2.503167  0.499649  0.563706   
2   -2.159336 -0.090580  0.260888  ...  -2.545144 -0.658411 -0.423618   
3   -0.250227 -0.620329 -1.343189  ...  -0.040887  0.017843  0.332572   
4    0.303635  0.861126 -2.024719  ...   0.844431  1.014944 -0.618231   
..        ...       ...       ...  ...        ...       ...       ...   
512  0.766946  0.818745 -0.289632  ...   0.300522  0.513876  0.539642   
513  0.107226  1.340049 -0.147246  ...   0.342367  0.485571  0.580150   
514  0.123010  1.290364 -0.177553  ...   0.332816  0.344047  0.122409   
515 -1.398344  0.076379 -0.005814  ...  -0.011739 -1.035533 -0.774382   
516  8.121827 -0.627980  4.953722  ...  10.467443 -7.333036  0.377340   

         pc19      pc20      pc21      pc22      pc23      pc24  size_category  
0    0.563603 -0.439596 -0.926619 -0.405425 -0.118719 -0.017933              0  
1   -0.703319 -1.535718 -0.892995  0.836590  0.204975  0.290771              0  
2    0.860550 -1.195230 -0.297870  0.743648  0.081757  0.345915              0  
3    1.164745 -1.632741 -0.817618  1.523710 -0.342302 -0.378420              0  
4    0.822853 -1.794109 -0.723371  2.020419 -0.545591  0.161735              0  
..        ...       ...       ...       ...       ...       ...            ...  
512 -0.052958  1.898628 -1.441786 -0.821192 -1.205707 -0.698666              1  
513  0.384984  0.086251 -0.970693 -1.353365 -1.254890 -1.212175              1  
514  0.313948  0.211157 -0.777731 -1.736711 -1.154127 -1.230040              1  
515 -0.216315  0.515791  0.080575 -0.055548 -0.067502 -0.311027              0  
516  8.870354 -1.074288  2.382433  1.042850  0.296436  0.125099              0  

[517 rows x 25 columns]

In [11]:
array = finaldf.values
X = array[:,0:24]
Y = array[:,24]

In [12]:
from keras.models import Sequential
from keras.layers import Dense

In [13]:
model = Sequential()
model.add(Dense(12, input_dim=24, activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [14]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model
model.fit(X, Y, validation_split=0.3, epochs=150, batch_size=10)

Epoch 1/150
37/37 [==============================] - 5s 17ms/step - loss: 0.6847 - accuracy: 0.5596 - val_loss: 0.6682 - val_accuracy: 0.5769
Epoch 2/150
37/37 [==============================] - 0s 4ms/step - loss: 0.6260 - accuracy: 0.7091 - val_loss: 0.6440 - val_accuracy: 0.6410
Epoch 3/150
37/37 [==============================] - 0s 3ms/step - loss: 0.5815 - accuracy: 0.7645 - val_loss: 0.6371 - val_accuracy: 0.6795
Epoch 4/150
37/37 [==============================] - 0s 2ms/step - loss: 0.5522 - accuracy: 0.7673 - val_loss: 0.6403 - val_accuracy: 0.6731
Epoch 5/150
37/37 [==============================] - 0s 2ms/step - loss: 0.5348 - accuracy: 0.7701 - val_loss: 0.6515 - val_accuracy: 0.6795
Epoch 6/150
37/37 [==============================] - 0s 3ms/step - loss: 0.5216 - accuracy: 0.7812 - val_loss: 0.6586 - val_accuracy: 0.6859
Epoch 7/150
37/37 [==============================] - 0s 3ms/step - loss: 0.5110 - accuracy: 0.7812 - val_loss: 0.6647 - val_accuracy: 0.6859
Epoch 8/150


Epoch 59/150
37/37 [==============================] - 0s 3ms/step - loss: 0.2081 - accuracy: 0.9114 - val_loss: 0.8968 - val_accuracy: 0.7115
Epoch 60/150
37/37 [==============================] - 0s 3ms/step - loss: 0.2024 - accuracy: 0.9224 - val_loss: 0.9051 - val_accuracy: 0.7115
Epoch 61/150
37/37 [==============================] - 0s 3ms/step - loss: 0.1979 - accuracy: 0.9280 - val_loss: 0.9135 - val_accuracy: 0.7115
Epoch 62/150
37/37 [==============================] - 0s 3ms/step - loss: 0.1947 - accuracy: 0.9307 - val_loss: 0.9222 - val_accuracy: 0.7051
Epoch 63/150
37/37 [==============================] - 0s 2ms/step - loss: 0.1905 - accuracy: 0.9280 - val_loss: 0.9278 - val_accuracy: 0.7115
Epoch 64/150
37/37 [==============================] - 0s 3ms/step - loss: 0.1865 - accuracy: 0.9280 - val_loss: 0.9384 - val_accuracy: 0.7115
Epoch 65/150
37/37 [==============================] - 0s 3ms/step - loss: 0.1842 - accuracy: 0.9307 - val_loss: 0.9510 - val_accuracy: 0.6987
Epoch 

37/37 [==============================] - 0s 3ms/step - loss: 0.0823 - accuracy: 0.9723 - val_loss: 1.3118 - val_accuracy: 0.7564
Epoch 117/150
37/37 [==============================] - 0s 2ms/step - loss: 0.0793 - accuracy: 0.9751 - val_loss: 1.3338 - val_accuracy: 0.7564
Epoch 118/150
37/37 [==============================] - 0s 2ms/step - loss: 0.0779 - accuracy: 0.9695 - val_loss: 1.3411 - val_accuracy: 0.7564
Epoch 119/150
37/37 [==============================] - 0s 2ms/step - loss: 0.0775 - accuracy: 0.9751 - val_loss: 1.3560 - val_accuracy: 0.7564
Epoch 120/150
37/37 [==============================] - 0s 3ms/step - loss: 0.0974 - accuracy: 0.9584 - val_loss: 1.3912 - val_accuracy: 0.7436
Epoch 121/150
37/37 [==============================] - 0s 2ms/step - loss: 0.0808 - accuracy: 0.9695 - val_loss: 1.3721 - val_accuracy: 0.7500
Epoch 122/150
37/37 [==============================] - 0s 3ms/step - loss: 0.0737 - accuracy: 0.9751 - val_loss: 1.3628 - val_accuracy: 0.7500
Epoch 123/150

In [15]:
scores = model.evaluate(X, Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

17/17 [==============================] - 0s 2ms/step - loss: 0.4895 - accuracy: 0.9207
accuracy: 92.07%


# GasTurbines

In [16]:
gas=pd.read_csv("gas_turbines.csv")
gas

AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0      6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1      6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2      6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3      7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4      7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
15034  9.0301  1005.6  98.460  3.5421  19.164  1049.7  546.21  111.61  10.400   
15035  7.8879  1005.9  99.093  3.5059  19.414  1046.3  543.22  111.78  10.433   
15036  7.2647  1006.3  99.496  3.4770  19.530  1037.7  537.32  110.19  10.483   
15037  7.0060  1006.8  99.008  3.4486  19.377  1043.2  541.24  110.74  10.533   
15038  6.9279  1007.2  97.533  3.4275  19.306  1049.9  545.85  111.58  10.583   

           CO     NOX  
0      3.1547  82.722  
1      3.2363  82.776  
2      3.2012  82.468  
3      3.1923  82.670  
4      3.2484  82.311  
...       ...     ...  
15034  4.5186  79.559  
15035  4.8470  79.917  
15036  7.9632  90.912  
15037  6.2494  93.227  
15038  4.9816  92.498  

[15039 rows x 11 columns]

In [17]:
gas.describe()

AT           AP            AH          AFDP          GTEP  \
count  15039.000000  15039.00000  15039.000000  15039.000000  15039.000000   
mean      17.764381   1013.19924     79.124174      4.200294     25.419061   
std        7.574323      6.41076     13.793439      0.760197      4.173916   
min        0.522300    985.85000     30.344000      2.087400     17.878000   
25%       11.408000   1008.90000     69.750000      3.723900     23.294000   
50%       18.186000   1012.80000     82.266000      4.186200     25.082000   
75%       23.862500   1016.90000     90.043500      4.550900     27.184000   
max       34.929000   1034.20000    100.200000      7.610600     37.402000   

                TIT           TAT           TEY           CDP            CO  \
count  15039.000000  15039.000000  15039.000000  15039.000000  15039.000000   
mean    1083.798770    545.396183    134.188464     12.102353      1.972499   
std       16.527806      7.866803     15.829717      1.103196      2.222206   
min     1000.800000    512.450000    100.170000      9.904400      0.000388   
25%     1079.600000    542.170000    127.985000     11.622000      0.858055   
50%     1088.700000    549.890000    133.780000     12.025000      1.390200   
75%     1096.000000    550.060000    140.895000     12.578000      2.160400   
max     1100.800000    550.610000    174.610000     15.081000     44.103000   

                NOX  
count  15039.000000  
mean      68.190934  
std       10.470586  
min       27.765000  
25%       61.303500  
50%       66.601000  
75%       73.935500  
max      119.890000

In [18]:
gas.info

<bound method DataFrame.info of            AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0      6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1      6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2      6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3      7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4      7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
15034  9.0301  1005.6  98.460  3.5421  19.164  1049.7  546.21  111.61  10.400   
15035  7.8879  1005.9  99.093  3.5059  19.414  1046.3  543.22  111.78  10.433   
15036  7.2647  1006.3  99.496  3.4770  19.530  1037.7  537.32  110.19  10.483   
15037  7.0060  1006.8  99.008  3.4486  19.377  1043.2  541.24  110.74  10.533   
15038  6.9279  1007.2  97.533  3.4275  19.306  1049.9  545.85  111.58  10.583

In [24]:
X = gas.loc[:,['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'CDP', 'CO','NOX']]
y= gas.loc[:,['TEY']]

In [25]:
scaled = StandardScaler()
X = scaled.fit_transform(X)
y = scaled.fit_transform(y)

In [26]:
def baseline_model():
    model = Sequential()
    model.add(Dense(10, input_dim=10, activation='tanh'))
    model.add(Dense(1))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

In [28]:
from sklearn.model_selection import KFold
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import InputLayer,Dense

estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=50, batch_size=100, verbose=False)
kfold = KFold(n_splits=10)
results = cross_val_score(estimator, X, y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

<ipython-input-28-51265ac65770>:7: DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=50, batch_size=100, verbose=False)


Results: -0.11 (0.06) MSE


In [29]:
estimator.fit(X, y)
prediction = estimator.predict(X)
prediction

array([-0.99234176, -1.010748  , -1.0563956 , ..., -1.1024309 ,
       -1.0224961 , -0.98643094], dtype=float32)

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [31]:
estimator.fit(X_train, y_train)
prediction = estimator.predict(X_test)
prediction

array([-1.1094991 , -1.1712708 , -1.1171206 , ...,  0.21986715,
        1.624334  , -0.22306351], dtype=float32)

In [33]:
X = gas.drop(columns = ['TEY'], axis = 1) 
y = gas.iloc[:,7]
from sklearn.preprocessing import scale
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)
X_train_scaled = scale(X_train)
X_test_scaled = scale(X_test)
X_test_scaled

array([[ 0.82623246, -0.43954308, -0.25924569, ...,  0.10039242,
        -0.3796304 , -0.69217007],
       [ 0.35282087,  0.23279782,  0.80230139, ..., -1.18541222,
         0.39149515, -1.09475442],
       [ 0.32839008, -0.07135639,  0.25312287, ...,  0.01665304,
        -0.00296896, -0.31891741],
       ...,
       [-0.74071701,  0.37687087,  0.43427425, ...,  1.77157829,
        -1.00127821, -0.4818816 ],
       [-0.49965786, -0.39151873,  0.64680105, ..., -0.26517949,
        -0.48137538,  0.12808615],
       [ 0.13151427,  0.32884652,  0.98830762, ..., -1.40331469,
         0.13152215, -0.64456466]])

In [34]:
import tensorflow as tf
input_size = len(X.columns)
output_size = 1
hidden_layer_size = 50

model = tf.keras.Sequential([
                                
                               tf.keras.layers.Dense(hidden_layer_size, input_dim = input_size, activation = 'relu'),
                               tf.keras.layers.Dense(hidden_layer_size, activation = 'relu'),
                               tf.keras.layers.Dense(hidden_layer_size, activation = 'relu'),
                               tf.keras.layers.Dense(hidden_layer_size, activation = 'relu'),     
                               tf.keras.layers.Dense(output_size)
                             ])

In [35]:
optimizer = tf.keras.optimizers.SGD(learning_rate = 0.03)
model.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['MeanSquaredError'])
num_epochs = 100
early_stopping = tf.keras.callbacks.EarlyStopping(patience = 2)
model.fit(X_train_scaled, y_train, callbacks = early_stopping, validation_split = 0.1, epochs = num_epochs, verbose = 2)

Epoch 1/100
381/381 - 1s - loss: 2804.4971 - mean_squared_error: 2804.4971 - val_loss: 184.2228 - val_mean_squared_error: 184.2228 - 1s/epoch - 3ms/step
Epoch 2/100
381/381 - 1s - loss: 92.3735 - mean_squared_error: 92.3735 - val_loss: 68.8450 - val_mean_squared_error: 68.8450 - 529ms/epoch - 1ms/step
Epoch 3/100
381/381 - 1s - loss: 38.1880 - mean_squared_error: 38.1880 - val_loss: 28.0586 - val_mean_squared_error: 28.0586 - 529ms/epoch - 1ms/step
Epoch 4/100
381/381 - 1s - loss: 17.4415 - mean_squared_error: 17.4415 - val_loss: 14.8048 - val_mean_squared_error: 14.8048 - 519ms/epoch - 1ms/step
Epoch 5/100
381/381 - 1s - loss: 8.4472 - mean_squared_error: 8.4472 - val_loss: 7.0670 - val_mean_squared_error: 7.0670 - 554ms/epoch - 1ms/step
Epoch 6/100
381/381 - 1s - loss: 5.0498 - mean_squared_error: 5.0498 - val_loss: 4.9707 - val_mean_squared_error: 4.9707 - 531ms/epoch - 1ms/step
Epoch 7/100
381/381 - 1s - loss: 3.3102 - mean_squared_error: 3.3102 - val_loss: 3.1033 - val_mean_square

In [36]:
test_loss, mean_squared_error = model.evaluate(X_test_scaled, y_test)

47/47 [==============================] - 0s 2ms/step - loss: 1.7648 - mean_squared_error: 1.7648
